# Generated by Django 3.0.8 on 2020-09-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('model', models.CharField(choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010')], max_length=200, verbose_name='Model')),
                ('bike_number', models.CharField(max_length=200, verbose_name='Bike Number')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Buy Price')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Sale Price')),
                ('owner', models.CharField(max_length=200, verbose_name='Owner')),
                ('contact', models.BigIntegerField(blank=True, verbose_name='Contact')),
                ('stock', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=200, verbose_name='In Stock')),
                ('sanakhat', models.BooleanField(default=False, verbose_name='Sanakhat')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Sale Price')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('contact', models.BigIntegerField(blank=True, verbose_name='Contact')),
                ('date', models.DateField(verbose_name='Date')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_product', to='product.Incoming', verbose_name='Incoming')),
            ],
        ),
    ]
