# Generated by Django 3.0.8 on 2020-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
